import '../globals.css';
import { Atkinson_Hyperlegible } from 'next/font/google';
import CustomHead from 'components/CustomHead';

const atkinsonHyperlegible = Atkinson_Hyperlegible({
  weight: ['400', '700'],
  subsets: ['latin'],
});

const siteTitle = 'Create Next App';
const siteDescription = 'Generated by create next app';

type Props = {
  children: React.ReactNode;
  params: Promise<{ lang: string }>; // params is now a Promise
};

export default async function RootLayout({ children, params }: Props) {
  const { lang } = await params;

  return (
    <html lang={lang}>
      <CustomHead title={siteTitle} description={siteDescription} />
      <body className={`${atkinsonHyperlegible.className} antialiased`}>
        {children}
      </body>
    </html>
  );
}
