import '../globals.css';
import { Atkinson_Hyperlegible } from 'next/font/google';
import CustomHead from 'components/CustomHead';
import DictionaryProviderWrapper from '../DictionaryProviderWrapper';

// Configure the Atkinson Hyperlegible font including specific weights and character subsets
const atkinsonHyperlegible = Atkinson_Hyperlegible({
  weight: ['400', '700'], // Font weights to be used
  subsets: ['latin'], // Specify the character subsets for the font
});

// Constants for SEO metadata
const siteTitle = 'Create Next App'; // The title of the site
const siteDescription = 'Generated by create next app'; // A brief description of the site

// Define the props type for the RootLayout component
type Props = {
  children: React.ReactNode; // Children elements that will be rendered within this layout
  params: Promise<{ lang: string }>; // Language parameters passed as a Promise
};

// Asynchronous function that defines the root layout for pages in the chosen language
export default async function RootLayout({ children, params }: Props) {
  const { lang } = await params; // Await the params to get the selected language

  // Render the overall HTML structure of the page
  return (
    <DictionaryProviderWrapper>
      <html lang={lang}>
        {/* Set the language attribute of the HTML for accessibility */}
        <CustomHead title={siteTitle} description={siteDescription} />
        {/* Add site meta tags */}
        <body className={`${atkinsonHyperlegible.className} antialiased`}>
          {/* Apply the custom font and enable antialiasing */}
          {children}
        </body>
      </html>
    </DictionaryProviderWrapper>
  );
}
